### ISSUE TITLE
Paired-end files

### ISSUE THREAD

**Issue by alerubio** [gersteinlab/texp#2]
Hello.
How can I use paired-end files? 

$> ./TeXP.sh -f [FILE_NAME] -t [INT] -o [OUTPUT_PATH] n [SAMPLE_ID]
-f: Input file (fastq,fastq.gz,sra)
-t: Number of threads
-o: Output path (i.e. ./ or ./processed)
-n: Sample name (i.e. SAMPLE01)

thanks and bests

Alex

**Comment by fabiocpn** [comment]
Dear Alex, 

At this moment, TeXP does not support paired-end files. Mostly because is much harder to model the effect of the distribution of fragment length in RNA-seq paired-end libraries. We suggest to process P1 and P2 independently and averaging the results. Our experience suggests that P1 and P2 should have very similar RPKM unless there is some quality issue on P2, then, this should be discarded.

Best,
Fábio Navarro
